# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fraud_detection_pb2 as fraud__detection__pb2


class FraudDetectionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CacheOrder = channel.unary_unary(
                '/fraud_detection.FraudDetection/CacheOrder',
                request_serializer=fraud__detection__pb2.OrderRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.OrderResponse.FromString,
                )
        self.CheckUserFraud = channel.unary_unary(
                '/fraud_detection.FraudDetection/CheckUserFraud',
                request_serializer=fraud__detection__pb2.OrderRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.OrderResponse.FromString,
                )
        self.CheckCardFraud = channel.unary_unary(
                '/fraud_detection.FraudDetection/CheckCardFraud',
                request_serializer=fraud__detection__pb2.OrderRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.OrderResponse.FromString,
                )
        self.ClearOrder = channel.unary_unary(
                '/fraud_detection.FraudDetection/ClearOrder',
                request_serializer=fraud__detection__pb2.ClearRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.ClearResponse.FromString,
                )


class FraudDetectionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CacheOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCardFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CacheOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CacheOrder,
                    request_deserializer=fraud__detection__pb2.OrderRequest.FromString,
                    response_serializer=fraud__detection__pb2.OrderResponse.SerializeToString,
            ),
            'CheckUserFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserFraud,
                    request_deserializer=fraud__detection__pb2.OrderRequest.FromString,
                    response_serializer=fraud__detection__pb2.OrderResponse.SerializeToString,
            ),
            'CheckCardFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCardFraud,
                    request_deserializer=fraud__detection__pb2.OrderRequest.FromString,
                    response_serializer=fraud__detection__pb2.OrderResponse.SerializeToString,
            ),
            'ClearOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearOrder,
                    request_deserializer=fraud__detection__pb2.ClearRequest.FromString,
                    response_serializer=fraud__detection__pb2.ClearResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetection', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FraudDetection(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CacheOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetection/CacheOrder',
            fraud__detection__pb2.OrderRequest.SerializeToString,
            fraud__detection__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckUserFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetection/CheckUserFraud',
            fraud__detection__pb2.OrderRequest.SerializeToString,
            fraud__detection__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckCardFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetection/CheckCardFraud',
            fraud__detection__pb2.OrderRequest.SerializeToString,
            fraud__detection__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ClearOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/fraud_detection.FraudDetection/ClearOrder',
            fraud__detection__pb2.ClearRequest.SerializeToString,
            fraud__detection__pb2.ClearResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
