# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_verification.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"\x8a\x01\n\x0cOrderRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x02 \x01(\t\x12-\n\x05items\x18\x03 \x03(\x0b\x32\x1e.transaction_verification.Item\x12\x0b\n\x03\x63vv\x18\x04 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x05 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"!\n\rOrderResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x32\x81\x01\n\x17TransactionVerification\x12\x66\n\x11VerifyTransaction\x12&.transaction_verification.OrderRequest\x1a\'.transaction_verification.OrderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ORDERREQUEST']._serialized_start=61
  _globals['_ORDERREQUEST']._serialized_end=199
  _globals['_ITEM']._serialized_start=201
  _globals['_ITEM']._serialized_end=239
  _globals['_ORDERRESPONSE']._serialized_start=241
  _globals['_ORDERRESPONSE']._serialized_end=274
  _globals['_TRANSACTIONVERIFICATION']._serialized_start=277
  _globals['_TRANSACTIONVERIFICATION']._serialized_end=406
# @@protoc_insertion_point(module_scope)
