# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_executor.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14order_executor.proto\x12\x0eorder_executor\"!\n\x0bPingRequest\x12\x12\n\nreplica_id\x18\x01 \x01(\x05\"C\n\x0cPingResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"!\n\x0cHeartbeatMsg\x12\x11\n\tleader_id\x18\x01 \x01(\x05\"\x0e\n\x0cHeartbeatAck2\x9f\x01\n\rOrderExecutor\x12\x43\n\x04Ping\x12\x1b.order_executor.PingRequest\x1a\x1c.order_executor.PingResponse\"\x00\x12I\n\tHeartbeat\x12\x1c.order_executor.HeartbeatMsg\x1a\x1c.order_executor.HeartbeatAck\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_executor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PINGREQUEST']._serialized_start=40
  _globals['_PINGREQUEST']._serialized_end=73
  _globals['_PINGRESPONSE']._serialized_start=75
  _globals['_PINGRESPONSE']._serialized_end=142
  _globals['_HEARTBEATMSG']._serialized_start=144
  _globals['_HEARTBEATMSG']._serialized_end=177
  _globals['_HEARTBEATACK']._serialized_start=179
  _globals['_HEARTBEATACK']._serialized_end=193
  _globals['_ORDEREXECUTOR']._serialized_start=196
  _globals['_ORDEREXECUTOR']._serialized_end=355
# @@protoc_insertion_point(module_scope)
