{
 "title": "Minnie-monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "payment-commit-requests-total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "payment_commit_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "tracing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "a6e9ebaa", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "payment-service" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "payment-prepare-latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "payment_prepare_latency_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "order_executor_memory_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order-duration-millisecond",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "order_executor_order_duration_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "order-count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "order_executor_order_count_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}