{
 "title": "minnie Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "order-count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "order_executor_order_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "tracing",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "6ebb8859", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{service.name=\"order_executor\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "order-duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "order_executor_order_duration_milliseconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "memory-usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "order_executor_memory_usage_percent",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}